---
- hosts: internet_pi
  roles:
    - common

  pre_tasks:
    - name: Ensure apt cache is up to date.
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when:
        - ansible_facts.os_family == "Debian"

    - name: Ensure pacman cache is up to date
      become: true
      community.general.pacman:
        update_cache: true
      when:
        - ansible_facts.os_family == "Archlinux"

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_role:
        name: docker
      become: true

    - name: Set up Internet Monitoring.
      ansible.builtin.import_role:
        name: internet-monitoring
      when: monitoring_enable

    - name: Set up Pi Hole.
      ansible.builtin.import_role:
        name: pi-hole
      when: pihole_enable

    - name: Set up Unbound.
      ansible.builtin.import_role:
        name: unbound
      when: unbound_enable
      tags: unbound

    - name: Set up unbound-telemetry.
      ansible.builtin.import_role:
        name: unbound-telemetry
      when: unbound_telemetry_enable
      tags: unbound-telemetry

    - name: Set up SNMP.
      ansible.builtin.import_role:
        name: snmp
      when: snmp_enable
      tags: snmp

    - name: Set up RTSP.
      ansible.builtin.import_role:
        name: rtsp
      when: rtsp_enable
      tags: rtsp

    - name: Set up SMB.
      ansible.builtin.import_role:
        name: smb
      when: smb_enable
      tags: smb

    - name: Set up Home Assistant.
      ansible.builtin.import_role:
        name: home-assistant
      when: home_assistant_enable
      tags: home-assistant

    - name: Set up ZWaveJS.
      ansible.builtin.import_role:
        name: zwavejs
      when: home_assistant_enable
      tags: zwavejs

    - name: Set up Nextcloud.
      ansible.builtin.import_role:
        name: nextcloud
      when: nextcloud_enable
      tags: nextcloud

    - name: Set up Cloudflare DDNS.
      ansible.builtin.import_role:
        name: cloudflare-ddns
      when: cloudflare_ddns_enable
      tags: cloudflare-ddns

    - name: Set up Shelly Plug Monitoring.
      ansible.builtin.import_role:
        name: shelly-plug
      when: shelly_plug_enable

    - name: Set up Air Gradient Monitoring.
      ansible.builtin.import_role:
        name: airgradient
      when: airgradient_enable

    - name: Set up Starlink Monitoring.
      ansible.builtin.import_role:
        name: starlink
      when: starlink_enable
