---
- name: Create unbound-telemetry folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/unbound-telemetry"
    state: directory
    mode: 0755
  become: false

- name: Copy unbound-telemetry docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/unbound-telemetry-docker-compose.yml.j2
    dest: "{{ config_dir }}/unbound-telemetry/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart unbound-telemetry

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure unbound-telemetry is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/unbound-telemetry/"
    build: false
  become: false
