---
- name: Gather package facts.
  ansible.builtin.package_facts:
    manager: auto
  when: ansible_facts.userspace_bits == '32'

- name: Upgrade libseccomp2 to latest version (32-bit Debian).
  ansible.builtin.import_tasks: tasks/debian-libseccomp-update.yml
  when:
    - ansible_facts.os_family == "Debian"
    - ansible_facts.userspace_bits == '32'
    - ansible_facts.packages['libseccomp2'][0]['version'] is version('2.4.4', '<')

- name: Synchronize internet-monitoring directory.
  ansible.posix.synchronize:
    src: internet-monitoring
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false

- name: Copy templated internet-monitoring files into place.
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ config_dir }}/internet-monitoring/{{ item }}"
    mode: 0644
  with_items:
    - config.monitoring
    - prometheus.yml
    - pinghosts.yaml
    - dnstargets.yaml
    - snmptargets.yaml
  notify: Restart internet-monitoring

- name: Ensure internet-monitoring environment is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
