---
- name: Clone airgradient-prometheus repo.
  ansible.builtin.git:
    repo: https://github.com/geerlingguy/airgradient-prometheus
    dest: "{{ config_dir }}/airgradient-prometheus/"
    version: master
    accept_hostkey: true
  notify: Restart airgradient-prometheus

- name: Copy AirGradient docker-compose template.
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ config_dir }}/airgradient-prometheus/docker-compose.yml"
    mode: '0640'
  notify: Restart airgradient-prometheus

- name: Ensure AirGradient Prometheus exporter is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/airgradient-prometheus/"
    build: false

- name: Copy airgradient dashboard config to grafana
  ansible.builtin.copy:
    src: files/airgradient-air-quality.json
    dest: "{{ config_dir }}/internet-monitoring/grafana/provisioning/dashboards/"
    mode: 0644
