---
- name: Restart pi-hole
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/pi-hole/"
    build: false
    restarted: true

- name: Restart unbound
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/unbound/"
    build: false
    restarted: true

- name: Restart unbound-telemetry
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/unbound-telemetry/"
    build: false
    restarted: true

- name: Restart snmp
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/snmp/"
    build: false
    restarted: true

- name: Restart rtsp
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/rtsp/"
    build: false
    restarted: true

- name: Restart smb
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/smb/"
    build: false
    restarted: true

- name: Restart home-assistant
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/home-assistant/"
    build: false
    restarted: true

- name: Restart zwavejs
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/zwavejs/"
    build: false
    restarted: true

- name: Restart nextcloud
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/nextcloud/"
    build: false
    restarted: true

- name: Restart internet-monitoring
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/internet-monitoring/"
    build: false
    restarted: true

- name: Restart shelly-plug-prometheus
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/shelly-plug-prometheus/"
    build: false
    restarted: true

- name: Restart airgradient-prometheus
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/airgradient-prometheus/"
    build: false
    restarted: true

- name: Restart starlink-exporter
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/starlink-exporter/"
    build: false
    restarted: true
